- source/Inkore.UI.WPF.Modern.Controls/AutoSuggestBox/AutoSuggestBox.xaml
- source/Inkore.UI.WPF.Modern/ThemeResources/Dark.xaml
- source/Inkore.UI.WPF.Modern/ThemeResources/Light.xaml
在此之前当系统的主题色发生改变时文本框的强调色并不会跟着改变
> 修复TextBox边框强调色不同步问题

- source/iNKORE.UI.WPF.Modern.Controls/Controls/MessageBox/MessageBoxImageExtensions.cs
> Fix MessageBoxImage ToSymbol

- samples/WpfApp1/MainWindow.xaml
- source/iNKORE.UI.WPF.Modern/Controls/ScrollViewerEx.cs
The problem itself is generally the overriding of ScrollInfo
This is only used for smooth scrolling, which is disabled by default anyway
#81 
#61
> Fix Scroll

- source/iNKORE.UI.WPF.Modern.Controls/Controls/Windows/FlipView/FlipView.cs
- source/iNKORE.UI.WPF.Modern.Controls/Controls/Windows/FlipView/FlipView.xaml
- source/iNKORE.UI.WPF.Modern.Controls/Controls/Windows/TransitioningContentControl/TransitioningContentControl.xaml
@NotYoojun does this work for #130 ?
> flipview slider animation

- source/iNKORE.UI.WPF.Modern.Controls/Controls/Windows/InfoBar/InfoBar.xaml
> Infobar with text wrapping problem

- .github/workflows/build.yml
Use `actions/upload-artifact@v4` instead of `actions/upload-artifact@v3`
> Fix build workflow issue

- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/SliderPage.xaml
- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/SliderPage.xaml.cs
> Gallery Revamp: Slider Page

- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/StackPanelPage.xaml
- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/StackPanelPage.xaml.cs
> Gallery Revamp: StackPanel Page

- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/ProgressRingPage.xaml
- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/ProgressRingPage.xaml.cs
> Gallery Revamp: ProgressRing Page

- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/AcrylicPage.xaml
- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/AcrylicPage.xaml.cs
- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/IconElementPage.xaml
> Gallery Revamp: AcrylicBrush Page

- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/PasswordBoxPage.xaml
- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/PasswordBoxPage.xaml.cs
> Gallery Revamp: PasswordBox Page

- source/iNKORE.UI.WPF.Modern.Controls/Controls/Windows/PipsPager/PipsPager.cs
- source/iNKORE.UI.WPF.Modern/Controls/ScrollViewerEx.cs
- source/iNKORE.UI.WPF.Modern/Themes/Controls/PipsPager.xaml
fix #195 
- update scrollviewerex animation
- enable pipspager to use animations
Hey @NotYoojun , can u please take a look at the ScrollViewerEx AnimateScroll as it doesn't seem to update the scrollable range until after the offset value is set
> fix #195 pipspager animation

- source/iNKORE.UI.WPF.Modern.Controls/Controls/Windows/TimePicker/DateTimeComponentSelector.cs
- source/iNKORE.UI.WPF.Modern.Controls/Controls/Windows/TimePicker/TimePicker.cs
- source/iNKORE.UI.WPF.Modern.Controls/Controls/Windows/TimePicker/TimePicker.xaml
- source/iNKORE.UI.WPF.Modern/Themes/Schemes/Dark.xaml
- source/iNKORE.UI.WPF.Modern/Themes/Schemes/HighContrast.xaml
- source/iNKORE.UI.WPF.Modern/Themes/Schemes/Light.xaml
- source/iNKORE.UI.WPF.Modern/Themes/ThemeResources.xaml
Fix for #145 
Update:
- timepicker style
- time components navigation buttons
- focus visual navigation
> [STYLE] TimePicker

- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/SplitButtonPage.xaml
- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/SplitButtonPage.xaml.cs
> Gallery Revamp: Split Button Page

- source/iNKORE.UI.WPF.Modern.Controls/Controls/Windows/RatingControl/RatingControl.xaml
- source/iNKORE.UI.WPF.Modern/Themes/Schemes/Dark.xaml
- source/iNKORE.UI.WPF.Modern/Themes/Schemes/HighContrast.xaml
- source/iNKORE.UI.WPF.Modern/Themes/Schemes/Light.xaml
- updated ratingcontrol style and relevant themeresources to match winui
Resolve #131
> [STYLE] RatingControl

- source/iNKORE.UI.WPF.Modern.Controls/Controls/Windows/NavigationView/NavigationView.properties.cs
Reverts iNKORE-NET/UI.WPF.Modern#287
> Revert "[BugFix] NavigationView initial state"

- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/ProgressBarPage.xaml
> Gallery Revamp: ProgressBar Page

- source/iNKORE.UI.WPF.Modern.Gallery/Pages/AllControlsPage.xaml
> Gallery Revamp: All Controls Page

- source/iNKORE.UI.WPF.Modern.Gallery/App.xaml
- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/ContentDialogTestWindow.xaml
- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/TestContentDialog.xaml
- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/TestContentDialog.xaml.cs
Fixes #256
Content dialog window:
> Gallery Revamp: Content Dialog Page

- source/iNKORE.UI.WPF.Modern.Gallery/Navigation/NavigationRootPage.xaml.cs
- source/iNKORE.UI.WPF.Modern.Gallery/Pages/SearchResultsPage.xaml
- source/iNKORE.UI.WPF.Modern.Gallery/Pages/SearchResultsPage.xaml.cs
- source/iNKORE.UI.WPF.Modern.Gallery/Themes/ItemTemplates.xaml
> Gallery Revamp: SearchResult Page

- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/NavigationViewPage.xaml
- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/NavigationViewPage.xaml.cs
- source/samples/SamplesCommon/SamplePages/SamplePage1.xaml
- source/samples/SamplesCommon/SamplePages/SamplePage2.xaml
- source/samples/SamplesCommon/SamplePages/SamplePage3.xaml
- source/samples/SamplesCommon/SamplePages/SamplePage4.xaml
- source/samples/SamplesCommon/SamplePages/SamplePage5.xaml
- source/samples/SamplesCommon/SamplePages/SamplePage6.xaml
- source/samples/SamplesCommon/SamplePages/SamplePage7.xaml
- source/samples/SamplesCommon/SamplePages/SampleSettingsPage.xaml
> Gallery Revamp: NavigationView Page

- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/CommandBarFlyoutPage.xaml
- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/CommandBarFlyoutPage.xaml.cs
Fixes #141 
Left Click:
Right Click:
> Gallery Revamp: CommandBarFlyout Page

- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/ParallaxViewPage.xaml
- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/ParallaxViewPage.xaml.cs
> Gallery Revamp: ParallaxView Page

- source/iNKORE.UI.WPF.Modern.Gallery/Controls/UserControls/TypographyControl.xaml
- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Foundation/Design/TypographyPage.xaml
- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Foundation/Design/TypographyPage.xaml.cs
> Gallery-Fix: Typography page unusual bright brush card fix

- source/iNKORE.UI.WPF.Modern.Gallery/Controls/SampleCodePresenter.xaml.cs
> Gallery-Fix: Fix Blinking Carret Showing on Code Presenter

- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/CanvasPage.xaml
- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/FlipViewPage.xaml
- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/ItemsRepeaterPage.xaml
- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/PersonPicturePage.xaml
- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/PipsPagerPage.xaml
- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/RadialGradientBrushPage.xaml
- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/ToolTipPage.xaml
> Gallery Revamp: Control Example Alignment Fix

- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/ToggleSwitchPage.xaml
> Gallery Revamp: ToggleSwitch Page

- source/iNKORE.UI.WPF.Modern.Gallery/Pages/Controls/Windows/SplitViewPage.xaml
> Gallery Revamp: SplitView Page
